Added makefile to create virtual environment
abinashmeher999/pymediawiki pull request #11
Opened 2016-12-03 14:07 UTC by ayuhsya

Using the make command will install virtualenv if not installed and setup the venv in the project folder. Will also display messages to further activate the environment and run the sample code.

2016-12-03 14:11 UTC, abinashmeher999 commented
@ayuhsya Could you enable edits by maintainers? It's in the lower right corner. Thanks. I will review it soon.

2016-12-03 14:13 UTC, ayuhsya commented
It's already enabled.

2016-12-03 14:36 UTC, abinashmeher999 commented
@ayuhsya Couple of things.
`pip` doesn't work without sudo on my machine so, we need a way to handle that. And also make activate doesn't seem to work. It just says `/bin/sh: source: not found`.

2016-12-03 14:42 UTC, abinashmeher999 requested changes
I have more suggestions to add which i will make myself. Meanwhile if you could change these it would be great. Also you can squash both the commits, \`Date` doesn't really convey much.

2016-12-03 14:42 UTC, abinashmeher999 commented on Makefile
> +activate:
better if it checks for existence of `venv` first.

2016-12-03 14:42 UTC, abinashmeher999 commented on Makefile
> +TARGET: requirements.txt wiki_cat.py
This need not check for `requirements.txt` or `wiki_cat.py`.

2016-12-03 14:42 UTC, abinashmeher999 commented on Makefile
> +uninstall:
This should check for `venv` too.

2016-12-04 15:35 UTC, ayuhsya commented
@abinashmeher999 Hey, I've made the final changes, do I need to send another PR?

2016-12-04 15:40 UTC, ayuhsya commented
@abinashmeher999 Also, I was kinda noob in using the squash command and squashed my commits to your latest commit :neutral_face: .

2016-12-04 19:07 UTC, abinashmeher999 commented
@ayuhsya I don't have issues with merging this. But just so you know, what you did can be undone using `git reflog`. Do you want to try?

2016-12-04 19:25 UTC, ayuhsya commented
@abinashmeher999 Umm, if there are no issues with merging then I request you to merge it. It says in my fork that it's one commit ahead of your repository, so it's OK I think.

2016-12-04 19:38 UTC, abinashmeher999 commented
@ayuhsya Are you sure you have enabled edits. Because I keep getting this
```bash
git push ayushya slave
Username for 'https://github.com': abinashmeher999
Password for 'https://abinashmeher999@github.com': 
error: src refspec slave does not match any.
error: failed to push some refs to 'https://github.com/ayuhsya/wikipedia-category.git'
```

2016-12-04 19:41 UTC, ayuhsya commented
Yes, I'm very positive the "Allow edits from maintainers." on the lower right corner is checked. Maybe try with +slave to force push? :neutral_face:

2016-12-04 19:50 UTC, abinashmeher999 approved these changes

2016-12-04 19:52 UTC, abinashmeher999 commented
@ayuhsya Great work! :tada: Giving the output in red was thoughtful :slightly_smiling_face:

2016-12-04 19:53 UTC, merged

2016-12-04 19:54 UTC, ayuhsya commented
Why would I want to delete the branch? Do I have to make a new branch for every issue?

2016-12-04 19:56 UTC, abinashmeher999 commented
There's no need for the branch anymore because it has been merged with master. You can checkout a new branch from the latest master and start working on it.

2016-12-04 19:57 UTC, ayuhsya commented
So then I have to merge my fork with the latest master?

2016-12-04 20:00 UTC, abinashmeher999 commented
Better yet rebase it.
```bash
git checkout master
git fetch upstream
git rebase upstream/master
git push origin master
```
This would work assuming your local master hasn't changed.

2016-12-04 20:13 UTC, abinashmeher999 commented
@ayuhsya An unfortunate result of that squashing incident is that your name now doesn't appear in the list of authors of commits. I am manually adding your name for now.