Added API props- contributors,links,redirects
abinashmeher999/pymediawiki pull request #40
Opened 2016-12-27 08:27 UTC by abhigyank

For issue #21 .
Added API properties -  contributors,links,redirects.
Changed _strip_JSON() parameters for different JSON response for different properties.

2016-12-27 09:13 UTC, abinashmeher999 commented
Hey @abhigyank, skimmed over it and it looks good! 💯 Please update your branch with the latest master. I will review it properly by today evening.

2016-12-28 15:44 UTC, abhigyank commented
Updated branch with latest master.

2016-12-28 16:30 UTC, abinashmeher999 requested changes

2016-12-28 16:30 UTC, abinashmeher999 commented on sample/core.py
> +        img_list = _strip_JSON(res, prop, 'File','title')
space after comma

2016-12-28 16:30 UTC, abinashmeher999 commented on sample/core.py
> +        lh_list = _strip_JSON(res, prop, '_nothing-to-strip_','title')
same as above

2016-12-28 16:30 UTC, abinashmeher999 commented on sample/core.py
> +        res = requests.get(self.base_url, params=self.payload,headers=self.headers).json()
same as above

2016-12-28 16:30 UTC, abinashmeher999 commented on sample/core.py
> +            res = requests.get(self.base_url, params=self.payload,headers=self.headers).json()
same here

2016-12-28 16:30 UTC, abinashmeher999 commented on sample/core.py
> +    def get_links(self,pllimit="max", pldir="ascending"):
and here

2016-12-28 16:30 UTC, abinashmeher999 commented on sample/core.py
> +        res = requests.get(self.base_url, params=self.payload,headers=self.headers).json()
same. space needed after comma

2016-12-28 16:30 UTC, abinashmeher999 commented on sample/core.py
> +            res = requests.get(self.base_url, params=self.payload,headers=self.headers).json()
here too

2016-12-28 16:30 UTC, abinashmeher999 commented on sample/core.py
> +    pprint(wk.get_redirects())
Also could you just print the name of the command before it actually prints. Easier that way to verify in the travis log.

2016-12-28 16:30 UTC, abinashmeher999 commented on sample/core.py
> +        self.payload['pccontinue'] = None
I just noticed this. This has been followed for all the other methods. Ideally the key `pccontinue` and its value should be deleted from the dict after use in this method. Could you please do the same for the rest of the methods too in a separate commit?

2016-12-28 16:57 UTC, abhigyank commented on sample/core.py
> +            res = requests.get(self.base_url, params=self.payload,headers=self.headers).json()
Is there any automated process to check this or do you just do manually?

2016-12-28 16:59 UTC, abinashmeher999 commented on sample/core.py
> +            res = requests.get(self.base_url, params=self.payload,headers=self.headers).json()
There are usually plugins for editors that do these checks according to PEP8. You can google if there are any for editor of your choice. For this PR I did manually.

2016-12-28 17:50 UTC, abinashmeher999 approved these changes

2016-12-28 17:54 UTC, merged