Minor refactoring in the project
abinashmeher999/pymediawiki pull request #44
Opened 2017-01-28 19:25 UTC by ayuhsya

- Rename `sample/` to `pymediawiki/`

- Created `helpers.py`: Has methods to fetch results of two different kinds.

- Created `constants.json`: Contains `property`:`prefix` key value pairs, to generate `continuetag` in `helpers.py`.

2017-01-28 22:37 UTC, abinashmeher999 commented
You are being modest by saying that this is minor :smile:. Looks great! Will review it tomorrow. Thanks for doing it.

2017-01-30 16:07 UTC, abinashmeher999 requested changes
Everything else looks good.

2017-01-30 16:07 UTC, abinashmeher999 commented on pymediawiki/helpers.py
> +def _fetch_results(url, payload, headers, prop, strip_chars, entry_prop):
@ayuhsya I think all instances of `_fetch_results` can be replaced with `_fetch_dict_results`. The places where we are using the former should also return the correct result when the `WikiPage` is instantiated with multiple page ids.

2017-01-30 17:08 UTC, ayuhsya commented on pymediawiki/helpers.py
> +def _fetch_results(url, payload, headers, prop, strip_chars, entry_prop):
Okay, but then the response would be an array of `dict` objects and not an array of strings as it is, presently, using the `_fetch_results` method.

2017-01-30 19:31 UTC, abinashmeher999 commented on pymediawiki/helpers.py
> +def _fetch_results(url, payload, headers, prop, strip_chars, entry_prop):
Yeah, no problem. Let us go with the generic approach (the one returning dictionary) for now. The interface for single and multiple pages will need a little more thought.

2017-02-02 13:46 UTC, abinashmeher999 approved these changes

2017-02-02 13:46 UTC, merged